import Head from "next/head";
import ProductCard from "@/components/ProductCard";

export default function Home({ products }) {
	console.log("Shop Rerendering");
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div>
					<div className="page-banner">
						<div className="page-banner__details">
							<div className="page-banner__details__title">
								<h1>Our E-com site</h1>
							</div>
						</div>
					</div>
					<div className="section">
						<div className="container">
							<div className="section__head">
								<div className="product__details__title">
									<h2>All Products</h2>
								</div>
							</div>
							<div className="section__content">
								<div className="grid three">
									{products.map((product) => (
										<ProductCard
											key={product.id}
											product={product}
										/>
									))}
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}

export async function getStaticProps() {
	console.log("I am getStaticProps from shop page");
	const res = await fetch("http://localhost:4000/products");
	const products = await res.json();
	return { props: { products } };
}
